
server:
  port: 8008
  servlet:
    context-path: /${spring.application.name}

spring:
  application:
    name: reminder
  webflux:
    base-path: ${spring.application.name}
  boot:
    admin:
      client:
        url: ${SBA_SERVER_URL}
        username: ${SBA_SERVER_USER}
        password: ${SBA_SERVER_PASSWORD}
        instance:
          service-url: http://host.docker.internal:${server.port}/${spring.application.name}

dailybot:
  bot-token: ${TG_BOT_TOKEN} # Токен бота
  bot-name: ${TG_BOT_NAME} # Имя бота
  chat-id: ${TG_GROUP_CHAT_ID} # Идентификатор чата рассылки
  debug-chat-id: ${TG_DEBUG_GROUP_CHAT_ID} # Идентификатор чата для информирования об исключительных ситуациях
  send-messages: true  # Признак отправки сообщения
  check-execution-time: true # Признак проверки точного времени отправки сообщения
  daily-link-common: ${DAILY_LINK_COMMON} # Ссылка на общий дейли
  daily-link-1: ${DAILY_LINK_1} # Ссылка 1 команды
  daily-link-2: ${DAILY_LINK_2} # Ссылка 2 команды
  daily-link-3: ${DAILY_LINK_3} # Ссылка 3 команды
  daily-cron: ${DAILY_CRON}
  fw-cron: ${FW_CRON}

management:
  endpoints:
    web:
      exposure:
        include: health,info