
apiVersion: v1
kind: Namespace
metadata:
  name: daybot

---

apiVersion: v1
kind: Pod
metadata:
  name: ss-dailybot
  namespace: daybot
  labels:
    app.kubernetes.io/name: ss-dailybot
spec:
  containers:
    - name: ss-dailybot
      image: ss-dailybot:1.0
      imagePullPolicy: Never
      envFrom:
        - configMapRef:
            name: daybot-cm

---

apiVersion: v1
kind: Service
metadata:
  name: daybot-service
  namespace: daybot
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: ss-dailybot
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8008
      nodePort: 30001

---

apiVersion: batch/v1
kind: CronJob
metadata:
  name: daybot-cron
  namespace: daybot
spec:
  schedule: "0 7 * * MON-FRI" # time in UTC
  startingDeadlineSeconds: 60
  successfulJobsHistoryLimit: 0
  failedJobsHistoryLimit: 0
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: daybot-cron
              image: curlimages/curl
              imagePullPolicy: IfNotPresent
              command:
                - sh
                - -c
              args:
                - curl daybot-service/ss-dailybot/api/v1/send-message
          restartPolicy: OnFailure